version: "3.9"
services:
  sensorsmock:
    build: ./sensors
    container_name: sensor
    ports:
      - "3000:3000"
    depends_on:
      - ca-postapi
    environment:
      - SMART_THERMO_BUCKET=capstone-project-khan
      - CARBON_SENSE_URL=http://postapi:3001/api/collect/moisturemate_data
      - MOISTURE_MATE_URL=http://postapi:3001/api/collect/carbonsense_data
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
  ca-postapi:
    build: ./carbon-moist-api
    container_name: ca-postapi
    ports:
      - "3001:3001"
      


