version: "3.9"
services:
  sensorsmock:
    build: ./sensors
    container_name: sensor
    ports:
      - "3000:3000"
    depends_on:
      - ca-postapi
    environment:
      - SMART_THERMO_BUCKET=your-bucket-name
      - CARBON_SENSE_URL=http://ca-postapi:3001/api/fetch/carbonsense_data
      - MOISTURE_MATE_URL=http://ca-postapi:3001/api/fetch/moisturemate_data
      - AWS_ACCESS_KEY_ID=your-access-key
      - AWS_SECRET_ACCESS_KEY=your-secret-access-key
      - AWS_SESSION_TOKEN=your-access-token
  
  ca-postapi:  
    build: ./extract/carbon_moist_extraction
    container_name: ca-postapi
    depends_on:
      - broker
    environment:
      - KAFKA_BOOTSTRAP_SERVER= broker:29092
    ports:
      - "3001:3001"
      
  luxmeter-data:  
    build: ./extract/luxmeter_extraction
    container_name: luxmeter-data
    depends_on:
      - broker
      - sensorsmock
    environment:
      - KAFKA_BOOTSTRAP_SERVER= broker:29092
      - LUXMETER_URL=http://sensor:3000/api/luxmeter/
    ports:
      - "3003:3003"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    command: >
      /bin/sh -c "
      ((sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 3 --topic moisturemate)&) && /etc/confluent/docker/run;
      ((sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 3 --topic carbonsense)&) && /etc/confluent/docker/run;
      ((sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 3 --topic luxmeter)&) && /etc/confluent/docker/run;
      "
    restart: always
