version: "3.9"
services:
  minio:
    image: quay.io/minio/minio
    container_name: container_minio
    ports:
      - '9000:9000' # API
      - '9090:9090' # console
    command: minio server /data --console-address ":9090"
    environment:
      - MINIO_ENDPOINT_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio-data:/data
    profiles: ['main-app-service']

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/capstondeg01;
      exit 0;
      "
    profiles: ['main-app-service']
  
  sensorsmock:
    build: ./sensors
    container_name: sensor
    ports:
      - "3000:3000"
    depends_on:
      - ca-postapi
      - broker
    environment:
      - SMART_THERMO_BUCKET=capstondeg01
      - CARBON_SENSE_URL=http://ca-postapi:3001/api/fetch/carbonsense_data
      - MOISTURE_MATE_URL=http://ca-postapi:3001/api/fetch/moisturemate_data
      - MINIO_ENDPOINT_URL=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    links:
      - minio
    profiles: ['main-app-service']

  ca-postapi:
    build: ./extract/carbon_moist_extraction
    container_name: ca-postapi
    depends_on:
      - broker
    environment:
      - KAFKA_BOOTSTRAP_SERVER= broker:29092
    ports:
      - "3001:3001"
    profiles: ['main-app-service']
      
  luxmeter-data:  
    build: ./extract/luxmeter_extraction
    container_name: luxmeter-data
    depends_on:
      - broker
      - sensorsmock
    environment:
      - KAFKA_BOOTSTRAP_SERVER= broker:29092
      - LUXMETER_URL=http://sensor:3000/api/luxmeter/
    ports:
      - "3003:3003"
    profiles: ['main-app-service']
  
  smartthermo-data:  
    build: ./extract/smart_thermo_extraction
    container_name: smartthermo_container
    depends_on:
      - broker
      - sensorsmock
    environment:
      - KAFKA_BOOTSTRAP_SERVER= broker:29092
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_ENDPOINT_URL=http://minio:9000
    ports:
      - "3006:3006"
    profiles: ['main-app-service']

  postgres:
    image: postgres:15-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
    ports:
      - "5432:5432"
    profiles: ['kafka-server']

  transformation:
    build: ./transform
    container_name: transformation_container
    restart: always
    depends_on:
      - postgres
    network_mode:
      host
    ports:
        - "5000:5000"  
    environment:
      POSTGRES_URL: jdbc:postgresql://<CHANGE_POSTGRES_IP>:5432/mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres_container
      POSTGRES_TABLE: mytable

    profiles: ['main-app-service']

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    profiles: ['kafka-server']

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: always
    profiles: ['kafka-server']

  ml_model_deploy:
      build: ./ml_model_deploy
      container_name: ml_model_deploy
      ports:
        - "8000:8000"
      depends_on:
        - transformation
        - postgres
      environment:
        POSTGRES_IP: add-your-ip
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: mydb
      restart: always
        
      profiles: ['main-app-service']

volumes:
  minio-data: 
    external: true
